### ISSUE TITLE
Publish vscode-black to Open VSX

### ISSUE THREAD

**Issue by omhomurlu** [34j/vscode-black#9]
Dear extension author,
Please publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by 34j** [comment]
(Hello, I had my notifications turned off so it took me quite a while to notice. My apologies.)

If you really need this extension, please send me a Pull Request with the Github Actions added.
Or you can register it on your own since this repository is MIT licensed.

Otherwise, sorry, but I am busy and this will not be done right away.

**Comment by 34j** [comment]
On second thought, since we are using `semantic-release-vsceP, this can be accomplished simply by adding `OVSX_PAT` to the release.yml.
